const SCREENS = {
  LOGIN: 'login',
  REGISTER: 'register',
  HOME: 'HOME',
  BOOKING: 'BOOKING',
  ORDER_SCREEN: 'ORDER_SCREEN',
  BOOKING_SCREEN: 'BOOKING_SCREEN',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
  RECEIVE_BOOK_SCREEN: 'RECEIVE_BOOK_SCREEN',
  ACC_INFO_SCREEN: 'ACC_INFO_SCREEN',
  DRIVER_TRIP_SCREEN: 'DRIVER_TRIP_SCREEN',
};

export default SCREENS;
