const SCREENS = {
  LOGIN: 'login',
  REGISTER: 'register',
  HOME: 'HOME',
  BOOKING: 'BOOKING',
  ORDER_SCREEN: 'ORDER_SCREEN',
  BOOKING_SCREEN: 'BOOKING_SCREEN',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
};

export default SCREENS;
